let a = 18;
let b = 7;
console.log("a =", a);  
console.log("b =", b); 
console.log("a + '5' =", a + '5');  
console.log("a - '5' =", a - '5');  
console.log("true + b =", true + b); 
console.log("true + false =", true + false); 
console.log("null + b =", null + b); 
console.log("undefined + b =", undefined + b);
console.log("NaN + 'test' =", NaN + 'test');  
console.log("a && b =", a && b);  
console.log("0 || b =", 0 || b); 
console.log("a == '18' ->", a == '18'); 
console.log("b == true ->", b == true); 
console.log("'' == 0 ->", '' == 0);  
console.log("[1] + b =", [1] + b);  
console.log("[] + {} =", [] + {}); 
console.log("({} + []) =", ({} + []));  
